#Archivo con parametros necesarios en la ejecucion del proceso
#Parametros de carga a BBDD
database.schema.cap   = CAPSEM
database.schema.fin   = FINANZAS
database.schema.int   = INTERACCIONES
database.schema.kf    = KFACTOR
database.schema.pa    = PRODUCTO_ASIGNADO
database.schema.prd   = PRODUCTO
database.schema.vta   = VENTAS
database.user_old     = srv_migracion_bigdata
database.url          = jdbc:oracle:thin:@//smt-scan.tchile.local:1521/EXPLOTA
database.driver       = oracle.jdbc.driver.OracleDriver
secreto.key_old       = sec-oracle-srv-migracion-bigdata

database.user         = FINANZAS_PROC
database.osuser       = FINANZAS_PROC
secreto.scope         = secrets-ingestas
secreto.key           = sec-oracle-finanzas-proc

##RUTAS DE ENTRADA
in.fin.bango_diario                       = .raw_finanzas.bango_diario
in.fin.bango_mensual                      = .raw_finanzas.bango_mensual
in.fin.cuenta_corriente                   = .finanzas.cuenta_corriente
in.fin.docomo_diario                      = .raw_finanzas.docomo_diario
in.fin.docomo_mensual                     = .raw_finanzas.docomo_mensual
in.fin.sa_carrier_billing_sva             = .raw_finanzas.sa_carrier_billing_sva
in.fin.timwe_diario                       = .raw_finanzas.timwe_diario
in.fin.timwe_mensual                      = .raw_finanzas.timwe_mensual
in.int.casos                              = .interacciones.casos
in.int.diccionario_operadora              = .raw_interacciones.diccionario_operadora
in.int.oaptpd                             = .raw_interacciones.oaptpd
in.int.param_competencia_estimada_portab  = .raw_interacciones.param_competencia_estimada_portab
in.int.orden_movil                        = .interacciones.orden_movil
in.int_transvalor_fijo                    = .ventas.tbf_trans_valor
in.ods.ar_charge                          = .odschile.ar_charge
in.ods.ar_credit                          = .odschile.ar_credit
in.ods.ar_invoice                         = .odschile.ar_invoice
in.ods.ar_legal_document                  = .odschile.ar_legal_document
in.ods.assigned_billing_offer             = .odschile.assigned_billing_offer
in.ods.assigned_product                   = .odschile.assigned_product
in.ods.assigned_product_parameter         = .odschile.assigned_product_parameter
in.ods.benefit_billing_offers             = .odschile.benefit_billing_offers
in.ods.billing_cycle_instance             = .odschile.billing_cycle_instance
in.ods.charge_code                        = .odschile.charge_code
in.ods.charge_request                     = .odschile.charge_request
in.ods.commercial_criteria_rules          = .odschile.commercial_criteria_rules
in.ods.customer                           = .odschile.customer
in.ods.plan_promo_rel                     = .odschile.plan_promo_rel
in.ods.prd_offer_classifications          = .odschile.prd_offer_classifications
in.ods.product                            = .odschile.product
in.ods.prd_cat_param_rel                  = .odschile.prd_cat_param_rel
in.ods.product_billing_parameters         = .odschile.product_billing_parameters
in.ods.product_catalog                    = .odschile.product_catalog
in.ods.product_parameters                 = .odschile.product_parameters
in.ods.product_rel                        = .odschile.product_rel
in.ods.subscribers                        = .odschile.subscribers
in.ods.tax_code                           = .odschile.tax_code
in.pa.activacion_sva_carrier_billing      = .raw_producto_asignado.activacion_sva_carrier_billing
in.pa.catalogo_planes_asignado            = .producto_asignado.catalogo_planes_asignado
in.pa.detalle_producto_asignado           = .producto_asignado.detalle_producto_asignado
in.pa.param_movistar_full                 = .raw_producto_asignado.param_movistar_full
in.pa.param_planes_fijo                   = .raw_producto_asignado.param_planes_fijo
in.pa.parque_fijo_acceso                  = .producto_asignado.parque_fijo_acceso
in.pa.parque_fijo_detalle_oferta_asignada = .producto_asignado.parque_fijo_detalle_oferta_asignada
in.pa.parque_gvp                          = .producto_asignado.parque_gvp
in.pa.parque_starzplay                    = .raw_producto_asignado.parque_starzplay
in.pa.plan_asignado_movil                 = .producto_asignado.assigned_prdct_plan_movil
in.pa.tbln_parque_full                    = .raw_producto_asignado.tbln_parque_full
in.pa.tenencia_personas_v360              = .producto_asignado.tenencia_personas_v360
in.per.base_unica_riesgo                  = .raw_persona.base_unica_riesgo
in.per.mf_hist_evaluacion                 = .raw_persona.mf_hist_evaluacion
in.prd.catalogo_productos                 = .producto.catalogo_productos
in.prd.param_puntos_carrier_billing       = .raw_producto.param_puntos_carrier_billing
in.trf.trafico_diario_mediacion           = .trafico.trafico_diario_mediacion
in.trf.trafico_mensual_mediacion          = .trafico.trafico_mensual_mediacion
in.vis.detalle_parque_movil_believe       = .visualizacion.parque_movil_believe
in.vis.detalle_portabilidad_movil         = .visualizacion.detalle_portabilidad_movil
in.vta.maestro_ventas_sva_fijo            = .raw_ventas.maestro_ventas_sva_fijo
in.vta.transvalor_movil                   = .ventas.transvalor
in.vta.venta_masiva_movil                 = .ventas.venta_masiva_movil

##RUTAS DE SALIDA
out.int.altas_producto_fox_fijo                       = /modelos/interacciones/altas_producto_fox_fijo
out.fin.conciliacion_carrier_billing                  = /modelos/finanzas/conciliacion_carrier_billing
out.fin.gestion_proximo_cobro                         = /modelos/finanzas/gestion_proximo_cobro
out.fin.parque_facturacion                            = /modelos/finanzas/parque_facturacion
out.fin.puntaje_credito_parque                        = /modelos/finanzas/puntaje_credito_parque
out.fin.puntos_credito_carrier_billing                = /modelos/finanzas/puntos_credito_carrier_billing
out.pa.bajas_suscriptores_eliminacion_lista_negra_sva = /modelos/producto_asignado/bajas_suscriptores_eliminacion_lista_negra_sva
out.pa.catalogo_planes_asignado                       = /modelos/producto_asignado/catalogo_planes_asignado
out.pa.componentes_buzon_voz                          = /modelos/producto_asignado/componentes_buzon_voz
out.pa.conexion_segura                                = /modelos/producto_asignado/conexion_segura
out.pa.det_onumber_asignado_b2c                       = /modelos/producto_asignado/det_onumber_asignado_b2c
out.pa.det_trafico_asignado_b2c                       = /modelos/producto_asignado/det_trafico_asignado_b2c
out.pa.det_volte_asignado_b2c                         = /modelos/producto_asignado/det_volte_asignado_b2c
out.pa.detalle_producto_asignado                      = /modelos/producto_asignado/detalle_producto_asignado
out.pa.sva_carrier_billing_terra                      = /modelos/producto_asignado/sva_carrier_billing_terra
out.pa.movistar_play_no_cliente                       = /modelos/producto_asignado/movistar_play_no_cliente
out.pa.parque_fijo_precierre                          = /modelos/producto_asignado/parque_fijo_precierre
out.prd.catalogo_productos                            = /modelos/producto/catalogo_productos
out.vis.agrupado_plan_flexible_asignado               = /modelos/visualizacion/agrupado/plan_flexible_asignado
out.vis.agrupado_movistar_full_asignado               = /modelos/visualizacion/agrupado/movistar_full_asignado
out.vis.portabilidad_competencia                      = /modelos/visualizacion/portabilidad_competencia
